export const menuLocators = {
    leftMenuId: ".leftmenu",
    leftMenuLength: 6,
    topMenuId:"#topPanel",
    rightmenuId: "ul[class='button']",
    rightmenuLength: 3,
    header: "h1",
    aboutUsUrl:"about.htm",
    servicesUrl:"services.htm",
    productsUrl: "http://www.parasoft.com/jsp/products.jsp",
    locationUrl: "http://www.parasoft.com/jsp/pr/contacts.jsp",
    adminUrl: "admin.htm",
    homeUrl: "index.htm",
    contactUrl: "contact.htm",
    forumUrl: "http://forums.parasoft.com/",
    siteMapUrl: "sitemap.htm",
    copyRightId: ".copyright",
    copyRightText: "© Parasoft. All rights reserved.",
    visitId: ".visit",
    visitUrl: "http://www.parasoft.com/",
    logoId: ".logo",
    captionId: "#topPanel .caption",
    captionText: "Experience the difference",
    solutionsId:".Solutions",
    footerMainId: "#footermainPanel",
    footerId:"#footerPanel",
    

}